name: ci

on: [push, pull_request]

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.0.0
            - uses: avsm/setup-ocaml@v1.0
              with:
                  ocaml-version: '4.10.0+flambda'
            - uses: actions/cache@v1.1.2
              with:
                  path: ~/.opam/download-cache/
                  key: ${{ runner.os }}-ocaml-opam-${{ hashFiles('dune-project') }}
                  restore-keys: |
                      ${{ runner.os }}-ocaml-opam-
            - run: make dep
            - run: make coverage
            - uses: codecov/codecov-action@v1.0.5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  file: ./_coverage/coverage.json
